
CREATE TABLE People (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(255),
    SecretCode CHAR(12) NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE Reports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ReporterId INT NOT NULL,
    TargetId INT NOT NULL,
    ReportText TEXT NOT NULL,
    SubmittedAt DATETIME NOT NULL,
    FOREIGN KEY (ReporterId) REFERENCES People(Id),
    FOREIGN KEY (TargetId) REFERENCES People(Id),
);

CREATE TABLE Alerts (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    TargetId INT NOT NULL,
    WindowStart DATETIME NOT NULL,
    WindowEnd DATETIME NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (TargetId) REFERENCES People(Id),
);